apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
  namespace: hole
data:
  Config.json: |
    {
      "EmailSenderSettings":{
        "email":"youremail@your-email.com",
        "password":"your email token,replace it",
        "servername":"your email host",
        "port":"8000"
      }
    }